version: '3'
services:
  rails:
    build: ./rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - ./rails:/usr/src/tutorial
    links:
      - mysql
  mysql:
    image: mysql:8.0.11
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
volumes:
  mysql-data:
    driver: local
    
